version: '3.6'

services:

  shorten:
    build: ./
    depends_on:
      - postgres
    restart: always
    env_file: .env
    ports:
      - "80:80"
    environment:
      NODE_ENV: development
      PORT: 80
      HOST: 0.0.0.0
      BASE_DOMAIN: http://192.168.99.100
      DB_HOST: "postgres"
      DB_PORT: 5432
      DB_NAME: "admin"
      DB_USER: "admin"
      DB_PASSWORD: "admin"
      WAIT_HOSTS: postgres:5432

  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pg_admin:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  db_data:
  pg_admin:
